// Auth action types
export const AUTH_START = 'AUTH_START';
export const AUTH_USER_LOGIN_SUCCESS = 'AUTH_USER_LOGIN_SUCCESS';
export const AUTH_ADMIN_LOGIN_SUCCESS = 'AUTH_ADMIN_LOGIN_SUCCESS';
export const AUTH_ADMIN_VERIFY_SUCCESS = 'AUTH_ADMIN_VERIFY_SUCCESS';
export const RESEND_CODE_SUCCESS = 'RESEND_CODE_SUCCESS';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_MESSAGE = 'AUTH_MESSAGE';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const SET_HASH = 'SET_HASH';



// Backend
export const DASHBOARD_RESET = 'DASHBOARD_RESET';
export const DASHBOARD_START = 'DASHBOARD_START';
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';
export const DASHBOARD_FAIL = 'DASHBOARD_FAIL';

export const ATTENDANCE_REPORT_RESET = 'ATTENDANCE_REPORT_RESET';
export const ATTENDANCE_REPORT_START = 'ATTENDANCE_REPORT_START';
export const ATTENDANCE_REPORT_SUCCESS = 'ATTENDANCE_REPORT_SUCCESS';
export const ATTENDANCE_REPORT_FAIL = 'ATTENDANCE_REPORT_FAIL';

export const CANAL_RESET = 'CANAL_RESET';
export const CANAL_START = 'CANAL_START';
export const CANAL_SUCCESS = 'CANAL_SUCCESS';
export const CANAL_FAIL = 'CANAL_FAIL';

export const CUSTOMERS_RESET = 'CUSTOMERS_RESET';
export const CUSTOMERS_START = 'CUSTOMERS_START';
export const CUSTOMERS_SUCCESS = 'CUSTOMERS_SUCCESS';
export const CUSTOMERS_FAIL = 'CUSTOMERS_FAIL';

export const COMPANIES_RESET = 'COMPANIES_RESET';
export const COMPANIES_START = 'COMPANIES_START';
export const COMPANIES_SUCCESS = 'COMPANIES_SUCCESS';
export const COMPANIES_FAIL = 'COMPANIES_FAIL';

export const COUNTRIES_RESET = 'COUNTRIES_RESET';
export const COUNTRIES_START = 'COUNTRIES_START';
export const COUNTRIES_SUCCESS = 'COUNTRIES_SUCCESS';
export const COUNTRIES_FAIL = 'COUNTRIES_FAIL';

export const CITIES_RESET = 'CITIES_RESET';
export const CITIES_START = 'CITIES_START';
export const CITIES_SUCCESS = 'CITIES_SUCCESS';
export const CITIES_FAIL = 'CITIES_FAIL';

export const AGENCIES_RESET = 'AGENCIES_RESET';
export const AGENCIES_START = 'AGENCIES_START';
export const AGENCIES_SUCCESS = 'AGENCIES_SUCCESS';
export const AGENCIES_FAIL = 'AGENCIES_FAIL';

export const EMPLOYEES_RESET = 'EMPLOYEES_RESET';
export const EMPLOYEES_START = 'EMPLOYEES_START';
export const EMPLOYEES_SUCCESS = 'EMPLOYEES_SUCCESS';
export const EMPLOYEES_FAIL = 'EMPLOYEES_FAIL';

export const EVENT_TYPES_RESET = 'EVENT_TYPES_RESET';
export const EVENT_TYPES_START = 'EVENT_TYPES_START';
export const EVENT_TYPES_SUCCESS = 'EVENT_TYPES_SUCCESS';
export const EVENT_TYPES_FAIL = 'EVENT_TYPES_FAIL';

export const JOBS_RESET = 'JOBS_RESET';
export const JOBS_START = 'JOBS_START';
export const JOBS_SUCCESS = 'JOBS_SUCCESS';
export const JOBS_FAIL = 'JOBS_FAIL';

export const PRIORITIES_RESET = 'PRIORITIES_RESET';
export const PRIORITIES_START = 'PRIORITIES_START';
export const PRIORITIES_SUCCESS = 'PRIORITIES_SUCCESS';
export const PRIORITIES_FAIL = 'PRIORITIES_FAIL';

export const MESSAGES_RESET = 'MESSAGES_RESET';
export const MESSAGES_START = 'MESSAGES_START';
export const MESSAGES_SUCCESS = 'MESSAGES_SUCCESS';
export const MESSAGES_FAIL = 'MESSAGES_FAIL';

export const CHAT_RESET = 'CHAT_RESET';
export const CHAT_START = 'CHAT_START';
export const CHAT_SUCCESS = 'CHAT_SUCCESS';
export const CHAT_MESSAGE_SUCCESS = 'CHAT_MESSAGE_SUCCESS';
export const CHAT_FAIL = 'CHAT_FAIL';